global using System.Reflection;
global using System.Security.Cryptography;
global using System.Text;
global using FluentResults;
global using FluentValidation.Results;
global using JCommunity.AppCore.Core.Abstractions;
global using JCommunity.AppCore.Core.BaseClasses;
global using JCommunity.AppCore.Core.Utils;
global using MediatR;
