name: Main_Action 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main


jobs:
  Build-Test:
    # if using self-hosted
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#action') }}
    steps:
     
      - uses: actions/checkout@v3
      
      - name: Set Local
        run: 
          LANG=ko_KR.utf8
          
      - name: Export Lang
        run:
          export LANG
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        # env:d
        #   DOTNET_INSTALL_DIR: "./.dotnet"
          
      - name: Restore
        run: dotnet restore ./JComunity.sln
        
      - name: Build
        run: dotnet build ./JComunity.sln --configuration Release --no-restore --utf8output
        
      - name: Test
        run: dotnet test ./JComunity.sln
        
