name: Main_Action 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main


jobs:
  Build-Test:
    # if using self-hosted
    #runs-on: self-hosted
    runs-on: windows-latest
    if: ${{ contains(github.event.head_commit.message, '#action') }}
    steps:
     
      - uses: actions/checkout@v3
               
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        # env:d
        #   DOTNET_INSTALL_DIR: "./.dotnet"
          
      - name: Restore
        run: dotnet restore ./JCommunity.sln
        
      - name: Build
        run: dotnet build ./JCommunity.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ./JCommunity.sln
        
